# This workflow will build a package using Maven and then publish it to GitHub packages when a push is done

name: Maven Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23 and configure Maven auth
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github                      # doit correspondre à <id> dans distributionManagement
          server-username: ${{ github.actor }}   # identité utilisée pour l'authentification
          server-password: ${{ secrets.GITHUB_TOKEN }}  # token pour GitHub Packages
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B deploy -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}